import {createI18n} from 'vue-i18n'
export const messages={
 el:{categoryLegendHint:'Πατήστε μια κατηγορία για απόκρυψη ή εμφάνιση στην πίτα.',app:'Οικία',subtitle:'Έξοδα πολυκατοικίας',dashboard:'Επισκόπηση',statements:'Μηνιαίες καταστάσεις',references:'Διαμερίσματα & κατηγορίες',projects:'Παρεμβάσεις',accounts:'Λογαριασμοί',login:'Σύνδεση',logout:'Αποσύνδεση',email:'Email',password:'Κωδικός πρόσβασης',welcome:'Η εικόνα της πολυκατοικίας σας',loginHint:'Πρόσβαση διαχειριστή · ιδιωτικά στοιχεία',save:'Αποθήκευση',cancel:'Ακύρωση',loading:'Φόρτωση…',empty:'Δεν υπάρχουν δημοσιευμένα στοιχεία ακόμη.',new:'Νέα κατάσταση',period:'Μήνας',total:'Σύνολο',status:'Κατάσταση',draft:'Πρόχειρο',published:'Δημοσιευμένο',superseded:'Προηγούμενη έκδοση',operating:'Λειτουργικά έξοδα',capital:'Κεφαλαιουχικά έξοδα',reserve:'Αποθεματικό',unclassified:'Χωρίς ταξινόμηση',from:'Από',to:'Έως',refresh:'Ενημέρωση',coverage:'Κάλυψη στοιχείων',apartment:'Διαμέρισμα',floor:'Όροφος',area:'Εμβαδόν (m²)',carLift:'Αναβατόριο αυτοκινήτων',active:'Ενεργό',name:'Όνομα',alias:'Αγγλική ονομασία',name_el:'Ελληνική ονομασία',name_en:'Αγγλική ονομασία',code:'Κωδικός',categories:'Κατηγορίες',add:'Προσθήκη',remove:'Αφαίρεση',issueDate:'Ημερομηνία έκδοσης',sections:'Ενότητες',lines:'Δαπάνες',rows:'Κατανομή διαμερισμάτων',section:'Ενότητα',category:'Κατηγορία',description:'Περιγραφή',amount:'Ποσό',classification:'Ταξινόμηση',source:'Πρωτότυπο',upload:'Μεταφόρτωση',review:'Έλεγχος',publish:'Δημοσίευση',revise:'Νέα αναθεώρηση',reviewed:'Επιβεβαίωσα τα στοιχεία με το πρωτότυπο',notes:'Σημειώσεις',exceptions:'Αιτιολογίες διαφορών',reason:'Αιτιολογία',delta:'Διαφορά',check:'Έλεγχος',revision:'Αναθεώρηση',boiler:'Νερό boiler (m³)',import:'Εισαγωγή CSV',export:'Εξαγωγή CSV',accountHint:'Δημιουργήστε λογαριασμούς διαμερισμάτων μόνο όταν είστε έτοιμοι για πρόσβαση κατοίκων.',saved:'Αποθηκεύτηκε',available:'Διαθέσιμο',missing:'Μη διαθέσιμο',common:'Κοινόχρηστα',lift:'Ανελκυστήρας',heating:'Θέρμανση',individual:'Ατομική θέρμανση',special:'Ειδικές',owners:'Ιδιοκτητών',equal:'Ίσα μέρη',standalone:'Αυτοτελή',issuance:'Έκδοση',closed:'Κλειστά',value:'Τιμή',blank:'Κενό (χωρίς χρέωση)',unreadable:'Δυσανάγνωστο',zero:'Μηδέν',raw:'Όπως τυπώθηκε',waterVolume:'Κατανάλωση νερού',usage:'Ατομική χρήση',commonWeight:'Χιλιοστά κοινών',liftWeight:'Χιλιοστά ανελκυστήρα',heatingWeight:'Χιλιοστά θέρμανσης',myApartment:'Το διαμέρισμά μου',yoy:'Μεταβολή από προηγούμενο έτος',noComparison:'Δεν υπάρχει συγκρίσιμη περίοδος',projectHint:'Καταγράψτε παρεμβάσεις με στοιχεία κόστους και ημερομηνίας. Η εξοικονόμηση είναι εκτίμηση.',completion:'Ολοκλήρωση',cost:'Κόστος',baseline:'Μηνιαία βάση',savings:'Εκτιμώμενη εξοικονόμηση',rotate:'Περιστροφή',zoom:'Μεγέθυνση',deleteDraft:'Διαγραφή προχείρου',confirmDelete:'Να διαγραφεί αυτό το πρόχειρο;',sourceTotal:'Τυπωμένο σύνολο',column:'Στήλη κατανομής',documents:'Αρχεία',months:'μήνες',private:'Ιδιωτικός χώρος διαχειριστή',history:'Ιστορικό αναθεωρήσεων',versionConflict:'Τα στοιχεία άλλαξαν. Φορτώστε ξανά.'},
 en:{categoryLegendHint:'Select a category to hide or show it in the pie.',app:'Oikia',subtitle:'Building expenses',dashboard:'Overview',statements:'Monthly statements',references:'Apartments & categories',projects:'Interventions',accounts:'Accounts',login:'Sign in',logout:'Sign out',email:'Email',password:'Password',welcome:'Your building at a glance',loginHint:'Administrator access · private records',save:'Save',cancel:'Cancel',loading:'Loading…',empty:'No published data yet.',new:'New statement',period:'Month',total:'Total',status:'Status',draft:'Draft',published:'Published',superseded:'Previous revision',operating:'Operating expenses',capital:'Capital expenses',reserve:'Reserve contributions',unclassified:'Unclassified',from:'From',to:'To',refresh:'Refresh',coverage:'Data coverage',apartment:'Apartment',floor:'Floor',area:'Area (m²)',carLift:'Car lift',active:'Active',name:'Name',alias:'English alias',name_el:'Greek name',name_en:'English name',code:'Code',categories:'Categories',add:'Add',remove:'Remove',issueDate:'Issue date',sections:'Sections',lines:'Expenses',rows:'Apartment allocations',section:'Section',category:'Category',description:'Description',amount:'Amount',classification:'Classification',source:'Original source',upload:'Upload',review:'Review',publish:'Publish',revise:'Create revision',reviewed:'I checked these values against the original',notes:'Notes',exceptions:'Difference explanations',reason:'Reason',delta:'Difference',check:'Check',revision:'Revision',boiler:'Boiler water (m³)',import:'Import CSV',export:'Export CSV',accountHint:'Create apartment accounts only when you are ready to grant resident access.',saved:'Saved',available:'Available',missing:'Unavailable',common:'Common',lift:'Passenger lift',heating:'Heating',individual:'Individual heating',special:'Special',owners:'Owners',equal:'Equal shares',standalone:'Standalone',issuance:'Issuance',closed:'Closed',value:'Value',blank:'Blank (no charge)',unreadable:'Unreadable',zero:'Zero',raw:'As printed',waterVolume:'Water consumption',usage:'Individual usage',commonWeight:'Common permille',liftWeight:'Lift permille',heatingWeight:'Heating permille',myApartment:'My apartment',yoy:'Year-over-year change',noComparison:'No comparable period',projectHint:'Record interventions with cost and date evidence. Savings are estimates.',completion:'Completion',cost:'Cost',baseline:'Monthly baseline',savings:'Estimated savings',rotate:'Rotate',zoom:'Zoom',deleteDraft:'Delete draft',confirmDelete:'Delete this draft?',sourceTotal:'Printed total',column:'Allocation column',documents:'Files',months:'months',private:'Private administrator workspace',history:'Revision history',versionConflict:'The records changed. Reload to continue.'}
}
Object.assign(messages.el,{sortByAmount:'Ταξινόμηση κατά ποσό',ascending:'Αύξουσα',descending:'Φθίνουσα'});
Object.assign(messages.en,{sortByAmount:'Sort by amount',ascending:'Ascending',descending:'Descending'});
Object.assign(messages.el,{priorYear:'Προηγούμενο έτος',allCategories:'Όλες οι κατηγορίες',rangeComparison:'Σύγκριση επιλεγμένης περιόδου με προηγούμενο έτος',boilerCharge:'Χρέωση boiler (€)',linkedCostHint:'Συνδέστε υπάρχουσες δαπάνες χωρίς δεύτερη καταχώριση κόστους.',targetCategories:'Κατηγορίες προς αξιολόγηση',baselinePeriods:'Μήνες βάσης (YYYY-MM, χωρισμένοι με κόμμα)',baselineNotes:'Μέθοδος βάσης, εξαιρέσεις και περιορισμοί',netBenefit:'Καθαρό εκτιμώμενο όφελος',insufficientEvidence:'Δεν υπάρχουν επαρκή στοιχεία για υπολογισμό.',completion_date_required:'Απαιτείται ημερομηνία ολοκλήρωσης',documented_cost_required:'Απαιτείται τεκμηριωμένο κόστος',target_categories_required:'Απαιτούνται κατηγορίες',documented_baseline_required:'Απαιτείται τεκμηριωμένη βάση',cost_source_superseded:'Αναθεωρήθηκε η πηγή κόστους',baseline_period_unavailable:'Μη διαθέσιμος μήνας βάσης',no_complete_post_month:'Δεν υπάρχει πλήρης μήνας μετά την ολοκλήρωση',period_not_complete:'Η περίοδος δεν έχει ολοκληρωθεί',baseline_must_precede_completion:'Η βάση πρέπει να προηγείται της ολοκλήρωσης',overlapping_project_categories:'Επικάλυψη κατηγοριών παρεμβάσεων',seasonal_baseline_missing:'Λείπει εποχική βάση',actual_missing:'Λείπει πραγματικό κόστος',unclassified_actual:'Υπάρχουν αταξινόμητα έξοδα'});
Object.assign(messages.en,{priorYear:'Previous year',allCategories:'All categories',rangeComparison:'Selected period versus previous year',boilerCharge:'Boiler charge (€)',linkedCostHint:'Link existing expense lines without recording their cost twice.',targetCategories:'Categories to assess',baselinePeriods:'Baseline months (YYYY-MM, comma-separated)',baselineNotes:'Baseline method, exclusions and limitations',netBenefit:'Net estimated benefit',insufficientEvidence:'Insufficient evidence for a calculation.',completion_date_required:'Completion date required',documented_cost_required:'Documented cost required',target_categories_required:'Target categories required',documented_baseline_required:'Documented baseline required',cost_source_superseded:'Cost source has been revised',baseline_period_unavailable:'Baseline month unavailable',no_complete_post_month:'No complete post-completion month',period_not_complete:'Period is not complete',baseline_must_precede_completion:'Baseline must precede completion',overlapping_project_categories:'Overlapping project categories',seasonal_baseline_missing:'Seasonal baseline missing',actual_missing:'Actual cost missing',unclassified_actual:'Unclassified actual expenses'});
Object.assign(messages.el,{sections_required:'Προσθέστε ενότητες.',lines_required:'Προσθέστε δαπάνες.',rows_required:'Προσθέστε διαμερίσματα.',source_required:'Επισυνάψτε το πρωτότυπο.',review_required:'Επιβεβαιώστε τον έλεγχο των στοιχείων.',missing_cell:'Λείπει κελί κατανομής',unreadable:'Δυσανάγνωστο',unmapped_cell:'Μη αντιστοιχισμένο ποσό',row:'Διαμέρισμα'});
Object.assign(messages.en,{sections_required:'Add sections.',lines_required:'Add expense lines.',rows_required:'Add apartment rows.',source_required:'Attach the original source.',review_required:'Confirm that you reviewed the source.',missing_cell:'Missing allocation cell',unreadable:'Unreadable',unmapped_cell:'Unmapped amount',row:'Apartment'});
Object.assign(messages.el,{estimatedMonth:'Εκτίμηση από δίμηνο',estimatedMonthHint:'Τα ποσά και η κατανάλωση νερού διαιρέθηκαν από κατάσταση δύο μηνών. Πηγή: {period}',estimatedComparison:'Η σύγκριση περιλαμβάνει εκτιμώμενο μήνα.',computedTotal:'Υπολογισμένο σύνολο',computedTotalHint:'Το σύνολο προκύπτει από τις ορατές χρεώσεις· η φωτογραφία κόβει το τυπωμένο σύνολο.',reportedTotal:'Σύνολο μήνα'});
Object.assign(messages.en,{estimatedMonth:'Estimated from two months',estimatedMonthHint:'Amounts and water usage were split from a two-month statement. Source: {period}',estimatedComparison:'Comparison includes an estimated month.',computedTotal:'Calculated total',computedTotalHint:'Total calculated from visible charges; the photo crops the printed total.',reportedTotal:'Monthly total'});
Object.assign(messages.el, {
 reportingPeriod: 'Περίοδος αναφοράς', selectMonthRange: 'Επιλέξτε περίοδο', chooseMonthRangeHint: 'Πατήστε τον πρώτο και μετά τον τελευταίο μήνα.', chooseLastMonth: 'Επιλέξτε τον τελευταίο μήνα.', chooseMonth: 'Επιλέξτε μήνα', latestMonths: 'Τελευταίοι {count} μήνες', allHistory: 'Όλο το ιστορικό', jumpToYear: 'Μετάβαση σε έτος', previousYear: 'Προηγούμενο έτος προβολής', nextYear: 'Επόμενο έτος προβολής', closePicker: 'Κλείσιμο επιλογής περιόδου', applyRange: 'Εφαρμογή', oneMonthSelected: '1 μήνας επιλεγμένος', monthsSelected: '{count} μήνες επιλεγμένοι',
});
Object.assign(messages.en, {
 reportingPeriod: 'Reporting period', selectMonthRange: 'Select a month range', chooseMonthRangeHint: 'Select the first month, then the last month.', chooseLastMonth: 'Select the last month.', chooseMonth: 'Choose a month', latestMonths: 'Latest {count} months', allHistory: 'All history', jumpToYear: 'Jump to year', previousYear: 'Previous display year', nextYear: 'Next display year', closePicker: 'Close month picker', applyRange: 'Apply range', oneMonthSelected: '1 month selected', monthsSelected: '{count} months selected',
});
Object.assign(messages.el, {
 recurringCosts: 'Επαναλαμβανόμενα έξοδα', recurringCostsHint: 'Μέσο κόστος και εύρος τιμών ανά ημερολογιακό μήνα, σε όλα τα έτη της περιόδου.', recurringExpense: 'Επαναλαμβανόμενη δαπάνη', statisticsPeriod: 'Περίοδος στατιστικών', selectedReportingPeriod: 'Επιλεγμένη περίοδος αναφοράς', averageCost: 'Μέσος όρος', minimumCost: 'Ελάχιστο', maximumCost: 'Μέγιστο', averageMonthlyCost: 'Μέσο μηνιαίο κόστος', minimumMonthlyCost: 'Χαμηλότερο μηνιαίο κόστος', maximumMonthlyCost: 'Υψηλότερο μηνιαίο κόστος', costRange: 'Ελάχιστο–μέγιστο', monthlySamples: 'Μήνες με στοιχεία: {count}', estimatedSamples: 'Εκτιμώμενοι μήνες: {count}', excludedMonths: 'Μη διαθέσιμοι μήνες που εξαιρέθηκαν: {count}', samples: 'Μήνες με στοιχεία', monthlyFigures: 'Μηνιαία ποσά', calculationMethod: 'Τρόπος υπολογισμού', recurringChartLabel: 'Μέσος όρος και εύρος μηνιαίου κόστους επαναλαμβανόμενης δαπάνης', noRecurringCosts: 'Δεν υπάρχουν ακόμη λειτουργικές δαπάνες σε τουλάχιστον δύο δημοσιευμένους μήνες.', recurringMethodHint: 'Η λίστα περιλαμβάνει κατηγορίες λειτουργικών εξόδων με μη μηδενική χρέωση σε τουλάχιστον δύο δημοσιευμένους μήνες του ιστορικού. Αθροίζουμε τις χρεώσεις κάθε κατηγορίας ανά μήνα και συγκρίνουμε τον ίδιο ημερολογιακό μήνα σε όλα τα έτη της επιλεγμένης περιόδου. Δημοσιευμένοι μήνες χωρίς χρέωση υπολογίζονται ως 0 €. Μη διαθέσιμες καταστάσεις εξαιρούνται. Οι εκτιμήσεις από δίμηνες καταστάσεις περιλαμβάνονται και επισημαίνονται. Κεφαλαιουχικά έξοδα, αποθεματικό και αταξινόμητες δαπάνες εξαιρούνται. Τα συνοπτικά ποσά αφορούν όλους τους διαθέσιμους μήνες της περιόδου.',
});
Object.assign(messages.en, {
 recurringCosts: 'Recurring expenses', recurringCostsHint: 'Average cost and price range for each calendar month, across the years in the period.', recurringExpense: 'Recurring expense', statisticsPeriod: 'Statistics period', selectedReportingPeriod: 'Selected reporting period', averageCost: 'Average', minimumCost: 'Minimum', maximumCost: 'Maximum', averageMonthlyCost: 'Average monthly cost', minimumMonthlyCost: 'Lowest monthly cost', maximumMonthlyCost: 'Highest monthly cost', costRange: 'Minimum–maximum', monthlySamples: 'Months with data: {count}', estimatedSamples: 'Estimated months: {count}', excludedMonths: 'Unavailable months excluded: {count}', samples: 'Months with data', monthlyFigures: 'Monthly figures', calculationMethod: 'How this is calculated', recurringChartLabel: 'Average and range of monthly recurring expense costs', noRecurringCosts: 'No operating expenses recorded in at least two published months yet.', recurringMethodHint: 'The selector includes operating categories charged a nonzero amount in at least two published months of history. We sum each category’s charges per month, then compare the same calendar month across all years in the chosen period. Published months without a charge count as €0. Unavailable statements are excluded. Estimates from two-month statements are included and flagged. Capital expenses, reserves and unclassified costs are excluded. Summary amounts cover all available months in the period.',
});
Object.assign(messages.el, {previousPage: 'Προηγούμενη σελίδα', nextPage: 'Επόμενη σελίδα', pageNumber: 'Σελίδα {page}', importPageNumber: 'Εισαγωγές · Σελίδα {page}'});
Object.assign(messages.en, {previousPage: 'Previous page', nextPage: 'Next page', pageNumber: 'Page {page}', importPageNumber: 'Imports · Page {page}'});
const locale=localStorage.getItem('locale')==='en'?'en':'el'
export const i18n=createI18n({legacy:false,locale,fallbackLocale:'el',messages})
