import { test, expect } from '@playwright/test'
import fs from 'node:fs'

test('local database reports update with the selected range on desktop and mobile', async ({ page }) => {
  const credentials = JSON.parse(fs.readFileSync(new URL('../../.local/admin-credentials.json', import.meta.url), 'utf8'))
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.clock.setFixedTime(new Date(2026, 9, 2, 12))
  const initialReport = page.waitForResponse(response => response.url().includes('/reports/building?from=2026-01&to=2026-10'))
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill(credentials.email)
  await page.getByLabel('Κωδικός πρόσβασης', { exact: true }).fill(credentials.password)
  await page.getByRole('button', { name: 'Σύνδεση', exact: true }).click()
  const trigger = page.getByRole('button', { name: /Περίοδος αναφοράς/ })
  await expect(trigger).toBeEnabled()
  const initialData = await (await initialReport).json()
  expect(initialData.coverage).toEqual({ published: 8, expected: 10 })
  expect(initialData.months.filter(month => !month.available).map(month => month.period)).toEqual(['2026-09', '2026-10'])
  await expect(trigger).toContainText('Ιαν 2026')
  await expect(trigger).toContainText('Οκτ 2026')
  await page.screenshot({ path: '../.local/year-to-date-dashboard.png' })
  await trigger.click()
  const picker = page.getByRole('dialog')
  await picker.getByRole('button', { name: 'Τελευταίοι 12 μήνες' }).click()
  await page.screenshot({ path: '../.local/month-range-desktop.png' })
  const report = page.waitForResponse(response => response.url().includes('/reports/building?from=2025-09&to=2026-08'))
  await picker.getByRole('button', { name: 'Εφαρμογή', exact: true }).click()
  expect((await (await report).json()).coverage).toEqual({ published: 12, expected: 12 })
  await expect(trigger).toBeEnabled()
  await expect(page.getByText('Κάλυψη στοιχείων: 12 / 12 μήνες', { exact: true })).toBeVisible()
  await expect(page.locator('.card.scroll').first().locator('tbody tr')).toHaveCount(12)
  await page.setViewportSize({ width: 390, height: 844 })
  await trigger.click()
  await expect(picker.getByRole('button', { name: 'Εφαρμογή', exact: true })).toBeVisible()
  const box = await picker.boundingBox()
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(390)
  const lastMonth = await picker.locator('[data-month="2026-12"]').boundingBox()
  const footer = await picker.locator('.range-footer').boundingBox()
  expect(lastMonth.y + lastMonth.height).toBeLessThanOrEqual(footer.y)
  await page.screenshot({ path: '../.local/month-range-mobile.png' })
  await picker.getByRole('button', { name: 'Ακύρωση', exact: true }).click()
  await expect(trigger).toBeFocused()
  expect(errors).toEqual([])
})
