import { test, expect } from '@playwright/test'
import fs from 'node:fs'

test('recurring expense widget works with local published history on desktop and mobile', async ({ page }) => {
  const credentials = JSON.parse(fs.readFileSync(new URL('../../.local/admin-credentials.json', import.meta.url), 'utf8'))
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill(credentials.email)
  await page.getByLabel('Κωδικός πρόσβασης', { exact: true }).fill(credentials.password)
  await page.getByRole('button', { name: 'Σύνδεση', exact: true }).click()
  const widget = page.locator('.recurring-costs')
  const selector = widget.getByLabel('Επαναλαμβανόμενη δαπάνη')
  await expect(selector).toBeVisible()
  expect(await selector.locator('option').count()).toBeGreaterThan(1)
  await widget.scrollIntoViewIfNeeded()
  await expect(widget.getByRole('img')).toBeVisible()
  await page.screenshot({ path: '../.local/recurring-costs-desktop.png' })
  await widget.getByText('Μηνιαία ποσά', { exact: true }).click()
  await expect(widget.locator('tbody tr')).toHaveCount(12)
  await widget.getByLabel('Περίοδος στατιστικών').selectOption('selected')
  await expect(widget.locator('.recurring-coverage')).toContainText('2026-01')
  await widget.getByLabel('Περίοδος στατιστικών').selectOption('history')
  await page.getByRole('combobox', { name: 'Language / Γλώσσα' }).selectOption('en')
  await widget.getByLabel('Recurring expense', { exact: true }).selectOption({ label: 'Common electricity' })
  await expect(widget.getByRole('rowheader', { name: 'January', exact: true })).toBeVisible()
  await widget.getByText('Monthly figures', { exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await widget.scrollIntoViewIfNeeded()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await widget.screenshot({ path: '../.local/recurring-costs-mobile.png' })
  expect(errors).toEqual([])
})
