<script setup>
import {ref,onMounted} from 'vue'
import {useI18n} from 'vue-i18n'
import {api,errorText} from '../api'
const {t,locale}=useI18n(),items=ref([]),candidates=ref([]),categories=ref([]),selected=ref(null),error=ref(''),result=ref(null),through=ref(new Date(new Date().getFullYear(),new Date().getMonth()-1,15).toISOString().slice(0,7)),baselineMonths=Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0')),periodText=ref('')
async function load(){items.value=(await api.get('/admin/projects')).data;candidates.value=(await api.get('/admin/project-candidates')).data;categories.value=(await api.get('/admin/references')).data.categories}
onMounted(load)
function edit(p){selected.value=p?JSON.parse(JSON.stringify(p)):{title:'',description:'',completion_date:null,target_categories:[],cost_line_ids:[],baseline:{},baseline_periods:[],baseline_notes:''};if(p)selected.value.cost_line_ids=p.cost_lines.map(x=>x.id);if(Array.isArray(selected.value.baseline))selected.value.baseline={};periodText.value=selected.value.baseline_periods.join(', ');result.value=null}
async function save(){try{let p=JSON.parse(JSON.stringify(selected.value));p.baseline=Object.fromEntries(Object.entries(p.baseline).filter(([,v])=>v!=='').map(([m,v])=>[m,String(v).includes(',')?String(v).replaceAll('.','').replace(',','.'):v]));p.baseline_periods=periodText.value.split(',').map(x=>x.trim()).filter(Boolean);const r=await api[p.id?'put':'post']('/admin/projects'+(p.id?'/'+p.id:''),p);await load();edit(r.data);error.value=''}catch(e){error.value=errorText(e)}}
async function calculate(){try{result.value=(await api.get(`/admin/projects/${selected.value.id}/savings`,{params:{through:through.value}})).data}catch(e){error.value=errorText(e)}}
</script>
<template><div class="toolbar"><h1>{{t('projects')}}</h1><button class="primary" @click="edit(null)">+ {{t('add')}}</button></div><p>{{t('projectHint')}}</p><p v-if="error" class="error">{{error}}</p><div class="card" v-for="p in items"><button @click="edit(p)">{{p.title}}</button> <span class="muted">{{p.completion_date||t('missing')}}</span></div><form v-if="selected" class="card" @submit.prevent="save"><div class="form-grid"><label>{{t('name')}}<input v-model="selected.title" required></label><label>{{t('completion')}}<input type="date" v-model="selected.completion_date"></label></div><label>{{t('description')}}<textarea v-model="selected.description"/></label><h2>{{t('cost')}}</h2><p class="muted">{{t('linkedCostHint')}}</p><label v-for="line in candidates" class="check"><input type="checkbox" v-model="selected.cost_line_ids" :value="line.id">{{line.description}} · {{line.amount}} € · {{line.period}}</label><h2>{{t('targetCategories')}}</h2><label v-for="c in categories" class="check"><input type="checkbox" v-model="selected.target_categories" :value="c.id">{{locale==='el'?c.name_el:c.name_en}}</label><h2>{{t('baseline')}}</h2><label>{{t('baselinePeriods')}}<input v-model="periodText" placeholder="2025-01, 2025-02"></label><div class="form-grid"><label v-for="m in baselineMonths">{{m}}<input v-model="selected.baseline[m]" inputmode="decimal" placeholder="EUR"></label></div><label>{{t('baselineNotes')}}<textarea v-model="selected.baseline_notes"/></label><div class="actions"><button class="primary">{{t('save')}}</button><button type="button" @click="selected=null">{{t('cancel')}}</button></div><div v-if="selected.id"><h2>{{t('savings')}}</h2><label>{{t('to')}}<input type="month" v-model="through"></label><button type="button" @click="calculate">{{t('review')}}</button><template v-if="result"><p v-if="!result.available" class="notice">{{t('insufficientEvidence')}} <span v-for="reason in result.reasons">{{t(reason.split(':')[0])}} {{reason.includes(':')?reason.split(':')[1]:''}}. </span></p><template v-else><p>{{t('savings')}}: {{result.cumulative}} € · {{t('netBenefit')}}: {{result.net}} €</p><div class="scroll"><table><thead><tr><th>{{t('period')}}</th><th>{{t('baseline')}}</th><th>{{t('amount')}}</th><th>{{t('savings')}}</th></tr></thead><tbody><tr v-for="m in result.months"><td>{{m.period}}</td><td>{{m.baseline}}</td><td>{{m.actual}}</td><td>{{m.savings}}</td></tr></tbody></table></div></template></template></div></form></template>
