<script setup>
import {ref,onMounted} from 'vue'
import {useI18n} from 'vue-i18n'
import {api,errorText} from '../api'
const {t}=useI18n(),data=ref({apartments:[],categories:[]}),error=ref(''),message=ref('')
onMounted(async()=>data.value=(await api.get('/admin/references')).data)
async function save(type,item){try{const r=await api[item.id?'put':'post'](`/admin/${type}${item.id?'/'+item.id:''}`,item);Object.assign(item,r.data);message.value=t('saved');error.value=''}catch(e){error.value=errorText(e)}}
</script>
<template><h1>{{t('references')}}</h1><p v-if="error" class="error">{{error}}</p><p v-if="message" class="notice">{{message}}</p><div class="card scroll"><button @click="data.apartments.push({label:'',alias:'',floor:1,area:null,car_lift:false,active:true})">+ {{t('apartment')}}</button><table><thead><tr><th>{{t('apartment')}}</th><th>{{t('alias')}}</th><th>{{t('floor')}}</th><th>{{t('area')}}</th><th>{{t('carLift')}}</th><th>{{t('active')}}</th><th/></tr></thead><tbody><tr v-for="a in data.apartments"><td><input v-model="a.label"></td><td><input v-model="a.alias"></td><td><input type="number" v-model="a.floor"></td><td><input type="number" v-model="a.area"></td><td><input type="checkbox" v-model="a.car_lift"></td><td><input type="checkbox" v-model="a.active"></td><td><button @click="save('apartments',a)">{{t('save')}}</button></td></tr></tbody></table></div><div class="card scroll"><h2>{{t('categories')}}</h2><button @click="data.categories.push({code:'',name_el:'',name_en:'',active:true})">+ {{t('add')}}</button><table><thead><tr><th>{{t('code')}}</th><th>{{t('name_el')}}</th><th>{{t('name_en')}}</th><th>{{t('active')}}</th><th/></tr></thead><tbody><tr v-for="c in data.categories"><td><input v-model="c.code"></td><td><input v-model="c.name_el"></td><td><input v-model="c.name_en"></td><td><input type="checkbox" v-model="c.active"></td><td><button @click="save('categories',c)">{{t('save')}}</button></td></tr></tbody></table></div></template>
