<script setup>
import {ref,onMounted} from 'vue'
import {useI18n} from 'vue-i18n'
import {api,errorText} from '../api'
import Editor from './StatementEditor.vue'
const {t,locale}=useI18n(),items=ref([]),selected=ref(null),error=ref(''),batches=ref([]),history=ref(false),page=ref(1),nextPage=ref(false),batchPage=ref(1),nextBatchPage=ref(false),loading=ref(false)
async function load(){loading.value=true;try{const [statements,imports]=await Promise.all([api.get('/admin/statements',{params:{history:history.value?1:0,per_page:24,page:page.value}}),api.get('/admin/imports',{params:{per_page:10,page:batchPage.value}})]);items.value=statements.data.data;nextPage.value=!!statements.data.next_page_url;batches.value=imports.data.data;nextBatchPage.value=!!imports.data.next_page_url;error.value=''}catch(e){error.value=errorText(e)}finally{loading.value=false}}
function changePage(step){page.value+=step;load()}
function changeBatchPage(step){batchPage.value+=step;load()}
async function open(id){selected.value=id}
async function importFile(e){try{let f=new FormData();f.append('file',e.target.files[0]);await api.post('/admin/imports',f);await load()}catch(e){error.value=errorText(e)}}
async function resume(id){try{await api.post(`/admin/imports/${id}/resume`);await load()}catch(e){error.value=errorText(e)}}
onMounted(load)
</script>
<template><Editor v-if="selected!==null" :id="selected" @close="selected=null;load()"/><div v-else><div class="toolbar"><div><span class="eyebrow">{{t('source')}}</span><h1>{{t('statements')}}</h1></div><div class="actions"><label class="file-button">{{t('import')}}<input type="file" accept=".csv" @change="importFile"></label><button class="primary" @click="open(0)">+ {{t('new')}}</button></div></div><p v-if="error" class="error" role="alert">{{error}}</p><label class="check"><input type="checkbox" v-model="history" @change="page=1;load()">{{t('history')}}</label><div class="card scroll"><table><thead><tr><th>{{t('period')}}</th><th>{{t('revision')}}</th><th>{{t('status')}}</th><th class="money">{{t('sourceTotal')}}</th><th></th></tr></thead><tbody><tr v-for="s in items" :key="s.id"><td>{{s.period}}</td><td>{{s.revision}}</td><td><span class="badge">{{t(s.status)}}</span></td><td class="money">{{new Intl.NumberFormat(locale,{style:'currency',currency:'EUR'}).format(s.printed_total)}}</td><td><button @click="open(s.id)">{{t('review')}}</button></td></tr></tbody></table><p v-if="!items.length">{{t('empty')}}</p></div><div class="actions pagination"><button :disabled="page===1 || loading" @click="changePage(-1)">{{t('previousPage')}}</button><span class="muted">{{t('pageNumber',{page})}}</span><button :disabled="!nextPage || loading" @click="changePage(1)">{{t('nextPage')}}</button></div><details v-for="b in batches" :key="b.id" class="card"><summary>{{b.name}} · {{b.items.filter(x=>x.status==='imported'||x.status==='existing').length}} / {{b.items.length}}</summary><button @click="resume(b.id)">{{t('refresh')}}</button><p v-for="(item,i) in b.items" :key="i">{{item.period}} · {{item.status}} {{item.error}}</p></details><div v-if="batches.length || batchPage>1" class="actions pagination"><button :disabled="batchPage===1 || loading" @click="changeBatchPage(-1)">{{t('previousPage')}}</button><span class="muted">{{t('importPageNumber',{page:batchPage})}}</span><button :disabled="!nextBatchPage || loading" @click="changeBatchPage(1)">{{t('nextPage')}}</button></div></div></template>
<style scoped>.pagination { margin: 0 0 1.2rem; }</style>
