<script setup>
import {ref,computed,onMounted} from 'vue'
import {useI18n} from 'vue-i18n'
import {api,apiUrl,errorText} from '../api'
const props=defineProps({id:Number}),emit=defineEmits(['close']),{t,locale}=useI18n()
const columns=['common','lift','heating','individual','boiler','special','owners','equal','standalone','issuance','closed']
const refs=ref({apartments:[],categories:[]}),s=ref(null),error=ref(''),message=ref(''),review=ref(null),tab=ref('lines'),busy=ref(false),rotation=ref(0),zoom=ref(100),document=ref(null),showSource=ref(false)
const editable=computed(()=>s.value?.status==='draft'),activeColumns=computed(()=>[...new Set(s.value?.sections.map(x=>x.allocation_column)||[])])
const knownWeights=[[74,63,66.8],[69,57,71.8],[74,68,66.8],[69,62,71.8],[149,140,153.2],[149,150,153.2],[149,160,153.2],[149,170,153.2],[118,130,110]]
function blankRow(a,i){return {apartment_id:a.id,printed_total:'0.00',metrics:{common_permille:String(knownWeights[i]?.[0]??''),lift_permille:String(knownWeights[i]?.[1]??''),heating_permille:String(knownWeights[i]?.[2]??''),boiler_m3:'',individual_usage:''},cells:columns.map(column=>({column,raw:'',state:'blank'}))}}
async function load(id=props.id){refs.value=(await api.get('/admin/references')).data;s.value=id?(await api.get('/admin/statements/'+id)).data:{period:'',issue_date:null,printed_total:'0.00',reviewed:false,exceptions:{},status:'draft',sections:[],lines:[],rows:refs.value.apartments.filter(a=>a.active).map(blankRow),documents:[],notes:''};if(Array.isArray(s.value.exceptions))s.value.exceptions={};for(const row of s.value.rows){for(const column of columns)if(!row.cells.some(c=>c.column===column))row.cells.push({column,raw:'',state:'blank'})}document.value=s.value.documents?.[0]??null;review.value=null}
onMounted(async()=>{try{await load()}catch(e){error.value=errorText(e)}})
function addSection(){const key=columns.find(c=>!s.value.sections.some(x=>x.key===c));if(!key)return;s.value.sections.push({key,label:t(key),allocation_column:key,printed_total:'0.00'})}
function addLine(){s.value.lines.push({section_key:s.value.sections[0]?.key||'',category_id:refs.value.categories[0]?.id,description:'',amount:'0.00',classification:'operating'})}
function canonical(v){const str=String(v??'').trim();return str.includes(',')?str.replaceAll('.','').replace(',','.'):str}
function payload(){const p=JSON.parse(JSON.stringify(s.value));p.printed_total=canonical(p.printed_total);for(const x of p.sections)x.printed_total=canonical(x.printed_total);for(const x of p.lines)x.amount=canonical(x.amount);for(const x of p.rows)x.printed_total=canonical(x.printed_total);return p}
async function save(){busy.value=true;error.value='';try{const p=payload();const result=s.value.id?await api.put('/admin/statements/'+s.value.id,p):await api.post('/admin/statements',p);await load(result.data.id);message.value=t('saved');return true}catch(e){error.value=errorText(e);return false}finally{busy.value=false}}
async function inspect(){if(editable.value&&!(await save()))return;try{review.value=(await api.get(`/admin/statements/${s.value.id}/review`)).data;tab.value='review'}catch(e){error.value=errorText(e)}}
async function publish(){if(!(await save()))return;try{await api.post(`/admin/statements/${s.value.id}/publish`,{version:s.value.version});await load(s.value.id)}catch(e){error.value=errorText(e)}}
async function revise(){try{const r=await api.post(`/admin/statements/${s.value.id}/revise`);await load(r.data.id)}catch(e){error.value=errorText(e)}}
async function upload(e){if(!s.value.id&&!(await save()))return;try{const f=new FormData();f.append('file',e.target.files[0]);const r=await api.post(`/admin/statements/${s.value.id}/documents`,f);s.value.documents.push(r.data);document.value=r.data}catch(e){error.value=errorText(e)}}
async function remove(){if(!window.confirm(t('confirmDelete')))return;try{await api.delete(`/admin/statements/${s.value.id}`,{data:{version:s.value.version}});emit('close')}catch(e){error.value=errorText(e)}}
function cell(row,column){return row.cells.find(x=>x.column===column)}
function unit(id){const a=refs.value.apartments.find(x=>x.id===id);return locale.value==='el'?a?.label:a?.alias}
</script>
<template><div v-if="s"><div class="toolbar"><div><button @click="emit('close')">← {{t('statements')}}</button><h1>{{s.period||t('new')}} <span class="badge">{{t(s.status)}}</span></h1></div><div class="actions"><a v-if="s.id" :href="apiUrl(`/admin/statements/${s.id}/export`)">{{t('export')}}</a><button v-if="s.status==='published'" @click="revise">{{t('revise')}}</button><button v-if="editable" class="primary" :disabled="busy" @click="save">{{t('save')}}</button><button v-if="s.id" @click="inspect">{{t('review')}}</button></div></div><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="message" class="notice" role="status">{{message}}</p><div class="card"><div class="form-grid"><label>{{t('period')}}<input v-model="s.period" type="month" :disabled="!!s.id"></label><label>{{t('issueDate')}}<input v-model="s.issue_date" type="date" :disabled="!editable"></label><label>{{t('sourceTotal')}}<input v-model="s.printed_total" inputmode="decimal" :disabled="!editable"></label></div><label>{{t('notes')}}<textarea v-model="s.notes" :disabled="!editable"/></label></div><div class="actions tabs"><button v-for="v in ['sections','lines','rows','source','review']" :key="v" @click="tab=v" :class="{primary:tab===v}">{{t(v)}}</button></div>
<label v-if="document&&tab!=='source'" class="check"><input v-model="showSource" type="checkbox">{{t('source')}}</label><div :class="{split:showSource&&document&&tab!=='source'}"><div v-if="showSource&&document&&tab!=='source'" class="card"><div class="actions"><button @click="rotation+=90">{{t('rotate')}}</button><input type="range" min="50" max="200" v-model="zoom" :aria-label="t('zoom')"></div><div class="viewer"><img v-if="document.mime!=='application/pdf'" class="source-image" :src="apiUrl(`/admin/documents/${document.id}`)" :alt="t('source')" :style="{transform:`rotate(${rotation}deg)`,width:zoom+'%'}"><iframe v-else :src="apiUrl(`/admin/documents/${document.id}`)" :title="t('source')" height="600"/></div></div><div>
<div v-if="tab==='sections'" class="card scroll"><button v-if="editable" @click="addSection">+ {{t('add')}}</button><table><thead><tr><th>{{t('section')}}</th><th>{{t('name')}}</th><th>{{t('column')}}</th><th>{{t('sourceTotal')}}</th><th/></tr></thead><tbody><tr v-for="(sec,i) in s.sections" :key="i"><td><select v-model="sec.key" :disabled="!editable"><option v-for="c in columns" :value="c">{{t(c)}}</option></select></td><td><input v-model="sec.label" :disabled="!editable"></td><td><select v-model="sec.allocation_column" :disabled="!editable"><option v-for="c in columns" :value="c">{{t(c)}}</option></select></td><td><input v-model="sec.printed_total" :disabled="!editable"></td><td><button v-if="editable" @click="s.sections.splice(i,1)">{{t('remove')}}</button></td></tr></tbody></table></div>
<div v-if="tab==='lines'" class="card scroll"><button v-if="editable" @click="addLine">+ {{t('add')}}</button><table><thead><tr><th>{{t('section')}}</th><th>{{t('category')}}</th><th>{{t('description')}}</th><th>{{t('amount')}}</th><th>{{t('classification')}}</th><th/></tr></thead><tbody><tr v-for="(line,i) in s.lines" :key="i"><td><select v-model="line.section_key" :disabled="!editable"><option v-for="sec in s.sections" :value="sec.key">{{sec.label}}</option></select></td><td><select v-model="line.category_id" :disabled="!editable"><option v-for="c in refs.categories" :value="c.id">{{locale==='el'?c.name_el:c.name_en}}</option></select></td><td><input v-model="line.description" :disabled="!editable"></td><td><input v-model="line.amount" inputmode="decimal" :disabled="!editable"></td><td><select v-model="line.classification" :disabled="!editable"><option v-for="c in ['operating','capital','reserve','unclassified']" :value="c">{{t(c)}}</option></select></td><td><button v-if="editable" @click="s.lines.splice(i,1)">{{t('remove')}}</button></td></tr></tbody></table></div>
<div v-if="tab==='rows'" class="card scroll"><table><thead><tr><th>{{t('apartment')}}</th><th v-for="c in activeColumns">{{t(c==='boiler'?'boilerCharge':c)}}</th><th>{{t('sourceTotal')}}</th><th>{{t('boiler')}}</th><th>{{t('usage')}}</th><th>{{t('commonWeight')}}</th><th>{{t('liftWeight')}}</th><th>{{t('heatingWeight')}}</th></tr></thead><tbody><tr v-for="row in s.rows" :key="row.apartment_id"><th>{{unit(row.apartment_id)}}</th><td v-for="c in activeColumns"><input v-model="cell(row,c).raw" :aria-label="unit(row.apartment_id)+' '+t(c)" :disabled="!editable" @input="cell(row,c).state=cell(row,c).raw?'value':'blank'"><select v-model="cell(row,c).state" :disabled="!editable" @change="cell(row,c).state==='zero'?cell(row,c).raw='0,00':cell(row,c).state==='blank'?cell(row,c).raw='':null"><option v-for="state in ['value','zero','blank','unreadable']" :value="state">{{t(state)}}</option></select></td><td><input v-model="row.printed_total" :disabled="!editable"></td><td v-for="m in ['boiler_m3','individual_usage','common_permille','lift_permille','heating_permille']"><input v-model="row.metrics[m]" :disabled="!editable"></td></tr></tbody></table></div>
<div v-if="tab==='source'" class="card"><label v-if="editable">{{t('upload')}}<input type="file" accept="image/jpeg,image/png,application/pdf" @change="upload"></label><div class="actions"><select v-model="document"><option v-for="d in s.documents" :value="d">{{d.filename}}</option></select><button @click="rotation+=90">{{t('rotate')}}</button><label>{{t('zoom')}}<input type="range" min="50" max="200" v-model="zoom"></label></div><div class="viewer" v-if="document"><iframe v-if="document.mime==='application/pdf'" :src="apiUrl(`/admin/documents/${document.id}`)" width="100%" height="600" :title="t('source')"/><img v-else class="source-image" :src="apiUrl(`/admin/documents/${document.id}`)" :alt="t('source')" :style="{transform:`rotate(${rotation}deg)`,width:zoom+'%'}"></div></div>
<div v-if="tab==='review'" class="card"><label class="check"><input v-model="s.reviewed" type="checkbox" :disabled="!editable">{{t('reviewed')}}</label><button @click="inspect">{{t('refresh')}}</button><template v-if="review"><p v-for="p in review.problems" class="error">{{t(p.split(':')[0])}} {{p.split(':').slice(1).join(' · ')}}</p><div class="scroll"><table><thead><tr><th>{{t('check')}}</th><th>{{t('delta')}}</th><th>{{t('reason')}}</th></tr></thead><tbody><tr v-for="c in review.checks" :key="c.key"><td>{{c.key.split(':').map(x=>t(x)).join(' · ')}}</td><td :class="{error:!c.accepted}">{{c.delta}}</td><td><input v-if="!c.matches" v-model="s.exceptions[c.key]" :disabled="!editable" :placeholder="t('reason')"><span v-else>✓</span></td></tr></tbody></table></div><button v-if="editable" class="primary" :disabled="!review.can_publish||busy" @click="publish">{{t('publish')}}</button></template><button v-if="editable&&s.id" @click="remove">{{t('deleteDraft')}}</button></div>
</div></div></div></template>
